### ISSUE TITLE
Repository find method acts weird when table has no primary_key set

### ISSUE THREAD

**Issue by bbonislawski** [hanami/model#374] opened 2017-01-23 22:50 UTC
I've created model without primary key with that migration:
```
Hanami::Model.migration do
  change do
    create_table :users do
      column :id, Integer
    end
  end
end
```
And then had some fun with repository
```
2.3.1 :036 > UserRepository.new.clear
 => 0 
2.3.1 :037 > UserRepository.new.create(id: 1)
 => #<User:0x007fcc2c67d658 @attributes={:id=>1}> 
2.3.1 :038 > UserRepository.new.find(1)
 => nil 
2.3.1 :039 > UserRepository.new.find(nil)
 => #<User:0x007fcc2c62ee18 @attributes={:id=>1}> 
2.3.1 :040 > UserRepository.new.create(id: 2)
 => #<User:0x007fcc2c5f7df0 @attributes={:id=>2}> 
2.3.1 :041 > UserRepository.new.find(nil)
ROM::TupleCountMismatchError: The relation consists of more than one tuple
```
It's a little weird and I hope I'll find some time to do more research on that

**Comment by beauby** [comment] 2017-01-23 23:00
I would consider the behavior of `Repository#find` to be undefined for tables without a primary key, though I agree that the `find(nil)` behavior (which seems to be "return all rows") is a bit surprising.
The fact that `find(1)` returns `nil` is what I expected.

**Comment by bbonislawski** [comment] 2017-01-23 23:05
Ok, I reconfigure my postgres to log everything and this is what I found `SELECT "id" FROM "users" WHERE (NULL IS NULL)` after calling `UserRepository.new.find(nil)`. That's quite surprising

**Comment by beauby** [comment] 2017-01-23 23:09
The corresponding line in hanami model is [that one](https://github.com/hanami/model/blob/master/lib/hanami/repository.rb#L375):
```ruby
    def find(id)
      root.by_primary_key(id).as(:entity).one
    end
```

`root` is a ROM relation, and I assume `#by_primary_key` is defined by ROM as well. The question is (cc @solnic), what is the expected behavior of ROM when calling `#by_primary_key` on a ROM relation that has no primary key?

**Comment by solnic** [comment] 2017-01-23 23:14
No, it's a bug in hanami-model right [here](https://github.com/hanami/model/blob/master/lib/hanami/repository.rb#L163-L165)

This should be fixed by using `by_pk` which is a built-in relation view provided by rom-sql

**Comment by beauby** [comment] 2017-01-23 23:19
@solnic My bad, I spoke too fast ;)
@bbonislawski Do you feel like taking care of this change?

**Comment by bbonislawski** [comment] 2017-01-23 23:25
I'll try my best!

**Comment by beauby** [comment] 2017-01-23 23:35
@bbonislawski Cool! Basically, as @solnic mentioned, you'll have to replace the call to `by_primary_key(id)` with `by_pk(id)` ([here](https://github.com/hanami/model/blob/master/lib/hanami/repository.rb#L375)), and remove the definition of `#by_primary_key` ([here](https://github.com/hanami/model/blob/master/lib/hanami/repository.rb#L163-L165)).

**Comment by bbonislawski** [comment] 2017-01-24 00:00
@beauby unfortunately, it doesn't fix the issue. `root.by_pk(nil)` returns something like
```
@relation=
  <ROM::Relation[Users] dataset=#<Sequel::Postgres::Dataset: "SELECT \"id\" FROM \"users\" WHERE (NULL IS NULL)">
```

**Comment by solnic** [comment] 2017-01-24 00:18
@bbonislawski uhm, I see what's going on, so you don't really had a PK in the db schema, that's why it's nil in the relation schema. I'll fix this in rom-sql by simply skipping definition of `by_pk` when `primary_key` is nil so this view won't exist. Not sure how to handle it in other places though, because we shouldn't require PK to exist (even though it's silly not to have one, but legacy dbs are all kinds of fun). I guess raising an error in repos would be a good solution (during setup phase).

**Comment by bbonislawski** [comment] 2017-01-24 00:24
I thought about defaulting to `:id` here https://github.com/rom-rb/rom-sql/blob/release-0.9/lib/rom/sql/relation.rb#L104 when `primary_key_name` is nil, but raising exception would be more reasonable imo, so it's better to do it that way.
Thanks for everything!

**Comment by jodosha** [comment] 2017-01-24 08:45
Hey, I'm sorry about this problem. I'm working on the fix.

**Comment by jodosha** [comment] 2017-01-24 09:28
Please review #375

**Closed** 2017-02-06 17:42 UTC
Labels: bug
